/* DAFTAR SEMUA BERKAS SURAT (satu baris per berkas di folder letters/).
 Dipakai letterRegistry.js untuk mencocokkan kartu katalog → berkas surat.
 Kolom: [slugBerkas, lingkup, kategori(tab), judul, kode, namaTemplatePdf]
 Surat baru: taruh berkasnya di letters/<group>/<slug>.vue, lalu tambahkan satu baris di sini dan satu entri di data/letterRegistry.js. */
export const LETTER_INDEX = [
  ["ktp-application-form", "general", "permohonan", "Surat Permohonan KTP", "KTP", "ktp-application-form"],
  ["resident-arrival-form", "general", "permohonan", "Formulir Permohonan Pindah Datang WNI", "SKD", "resident-arrival-form"],
  ["kia-application-form", "general", "permohonan", "Surat Permohonan Penerbitan KIA", "KIA", "kia-application-form"],
  ["temporary-resident-request", "general", "permohonan", "Surat Permohonan Menjadi Penduduk Sementara / SKTS", "PPS", "temporary-resident-request"],
  ["divorce-lawsuit-letter", "general", "permohonan", "Surat Permohonan Cerai", "GCR", "divorce-lawsuit-letter"],
  ["fuel-recommendation-letter", "general", "permohonan", "Surat Rekomendasi Pembelian Jenis BBM Tertentu", "BBM", "fuel-recommendation-letter"],
  ["temporary-stay-application-form", "general", "permohonan", "Permohonan Tinggal Sementara", "TSM", "temporary-stay-application-form"],
  ["relocation-cover-letter", "general", "permohonan", "Surat Pengantar Permohonan Pindah WNI", "PPN", "relocation-cover-letter"],
  ["relocation-certificate-form", "general", "permohonan", "Formulir Keterangan Pindah WNI", "SKP", "relocation-certificate-form"],
  ["population-occurrence-registration", "general", "permohonan", "Formulir Pendaftaran Peristiwa Kependudukan", "PPK", "population-occurrence-registration-form"],
  ["family-biodata", "general", "permohonan", "Formulir Biodata Penduduk WNI (Per Keluarga)", "BDK", "family-biodata-form"],
  ["birth-certificate-application-form", "general", "permohonan", "Permohonan Akta Kelahiran", "AKL", null],
  ["birth-report-form", "general", "permohonan", "Formulir Pelaporan Kelahiran (Untuk Mendapatkan Akta Kelahiran)", "LPK", null],
  ["death-certificate-application", "general", "permohonan", "Permohonan Akta Kematian", "AKM", null],
  ["death-report-form", "general", "permohonan", "Formulir Pelaporan Kematian (Untuk Mendapatkan Akta Kematian)", "LPM", null],
  ["marriage-application-letter", "general", "permohonan", "Permohonan Kehendak Nikah", "KHN", null],
  ["marriage-registration-data-sheet", "general", "permohonan", "Data Isian Pendaftaran Nikah", "DPN", null],
  ["registration-form", "general", "permohonan", "Data Isian Pendaftaran Nikah", "FPN", "registration-form"],
  ["identity-discrepancy-statement-letter", "general", "pernyataan", "Surat Pernyataan Beda Nama/Identitas", "PPI", "identity-discrepancy-statement-letter"],
  ["statement-population-data-change", "general", "pernyataan", "Surat Pernyataan Perubahan Elemen Data Kependudukan", "PDP", "statement-population-data-change"],
  ["population-document-statement-letter", "general", "pernyataan", "Surat Pernyataan Tidak Memiliki Dokumen Kependudukan", "PDK", "population-document-statement-letter"],
  ["unregistered-marriage-responsibility-letter", "general", "pernyataan", "Surat Pernyataan Tanggung Jawab Mutlak Perkawinan Belum Tercatat", "PNB", "unregistered-marriage-responsibility-letter"],
  ["heir-power-of-attorney-letter", "general", "pernyataan", "Surat Kuasa Sidang Waris", "KAW", "heir-power-of-attorney-letter"],
  ["population-service-authorization-letter", "general", "pernyataan", "Surat Kuasa Dalam Pelayanan Administrasi Kependudukan", "KPK", "population-service-authorization-letter"],
  ["birth-report-statement", "general", "pernyataan", "Laporan Kelahiran", "PLK", null],
  ["spousal-relationship-responsibility-statement", "general", "pernyataan", "Surat Pernyataan Tanggung Jawab Mutlak Kebenaran Sebagai Pasangan Suami Istri", "PHS", null],
  ["birth-certificate-power-of-attorney", "general", "pernyataan", "Surat Kuasa", "KAK", null],
  ["death-general-statement", "general", "pernyataan", "Surat Keterangan Mohon Akta Kematian", "PKU", null],
  ["death-data-statement", "general", "pernyataan", "Surat Pernyataan Tanggung Jawab Mutlak (SPTJM) Kebenaran Data Kematian", "PDM", null],
  ["death-power-of-attorney", "general", "pernyataan", "Surat Kuasa", "KKM", null],
  ["letter-c-data-statement-letter", "general", "pernyataan", "Surat Pernyataan Permohonan Data Letter C", "PLC", null],
  ["power-of-attorney-letter", "general", "pernyataan", "Surat Kuasa", "KLC", null],
  ["not-remarried-statement-letter", "general", "pernyataan", "Surat Keterangan Belum Menikah Lagi", "PBM", null],
  ["parental-consent-letter", "general", "pernyataan", "Surat Izin Orang Tua", "SOT", null],
  ["bride-groom-consent-letter", "general", "pernyataan", "Persetujuan Calon Pengantin", "SCM", null],
  ["guardian-statement", "general", "pernyataan", "Surat Keterangan Wali Nikah", "PWN", "guardian-statement"],
  ["unmarried-statement", "general", "pernyataan", "Surat Keterangan Belum Menikah Lagi", "PBN", "unmarried-statement"],
  ["unmarried-status-letter", "general", "keterangan", "Surat Keterangan Belum Kawin", "KSB", "unmarried-status-letter"],
  ["bussiness-permit-letter", "general", "keterangan", "Surat Keterangan Usaha", "IZU", "bussiness-permit-letter"],
  ["general-statement-letter", "general", "keterangan", "Surat Keterangan Umum", "SPU", "general-statement-letter"],
  ["domicile-certificate", "general", "keterangan", "Surat Keterangan Domisili", "KDM", "domicile-certificate"],
  ["sktm-general", "general", "keterangan", "Surat Keterangan Tidak Mampu", "SKTM", "sktm-general"],
  ["sktm-school", "general", "keterangan", "Surat Keterangan Tidak Mampu Sekolah", "SKTS", "sktm-school"],
  ["income-permit-letter", "general", "keterangan", "Surat Keterangan Penghasilan", "KPH", "income-permit-letter"],
  ["event-permit-letter", "general", "keterangan", "Surat Keterangan Keramaian", "IZK", "event-permit-letter"],
  ["travel-permit-letter-gov", "general", "keterangan", "Surat Keterangan Jalan", "IPI", "travel-permit-letter-gov"],
  ["skck-referral-letter", "general", "keterangan", "Surat Keterangan Mohon SKCK", "SKCK", "skck-referral-letter"],
  ["legalization-register", "general", "keterangan", "Surat Legalisasi", "LGL", "legalization-register"],
  ["birth-attestation-letter", "general", "keterangan", "Surat Keterangan Kelahiran", "KLH", null],
  ["death-certificate", "general", "keterangan", "Surat Keterangan Kematian", "KKT", null],
  ["death-commemoration-calculation", "general", "keterangan", "Perhitungan Selamatan 3 Hari Sampai 1000 Hari", "HPK", null],
  ["land-price-certificate-letter", "general", "keterangan", "Surat Keterangan Harga Tanah", "KHT", null],
  ["land-origin-certificate-letter", "general", "keterangan", "Surat Keterangan Asal Tanah", "KAT", null],
  ["never-married-certificate-letter", "general", "keterangan", "Surat Keterangan Belum Pernah Menikah", "KBP", null],
  ["marriage-lodging-certificate-letter", "general", "keterangan", "Surat Keterangan Numpang Nikah", "KNN", null],
  ["death-certificate-for-marriage-letter", "general", "keterangan", "Surat Keterangan Kematian", "KKN", null],
  ["general-certificate-letter", "general", "keterangan", "Surat Pengantar Tes Kesehatan", "KUM", null],
  ["unmarried-certificate", "general", "keterangan", "Surat Keterangan Belum Pernah Menikah", "KBM", "unmarried-certificate"],
  ["n1", "general", "keterangan", "Pengantar Nikah", "N1", "n1"],
  ["n2", "general", "keterangan", "Permohonan Kehendak Nikah", "N2", "n2"],
  ["n4", "general", "keterangan", "Persetujuan Calon Pengantin", "N4", "n4"],
  ["n5", "general", "keterangan", "Surat Izin Orang Tua", "N5", "n5"],
  ["n6", "general", "keterangan", "Surat Keterangan Kematian", "N6", "n6"],
  ["duty-travel-order-letter", "general", "perintah", "SPPD", "SPPD", "duty-travel-order-letter"],
  ["late-birth-registration-approval-decree", "general", "perintah", "Surat Pencatatan Kelahiran Terlambat", "SKT", null],
  ["permit-followup-letter", "general", "balasan", "Surat Tindak Lanjut Permohonan Izin", "TLP", "permit-followup-letter"],
  ["lease-offer-letter", "general", "balasan", "Surat Penawaran Sewa Kontrak Gedung BRI Unit Ngemplak II", "SPS", "lease-offer-letter"],
  ["research-response-letter", "general", "balasan", "Surat Balasan Penelitian", "BIP", "research-response-letter"],
  ["marriage-certificate-duplicate-letter", "general", "pengantar", "Surat Pengantar Duplikat Nikah", "DAN", "marriage-certificate-duplicate-letter"],
  ["general-cover-letter", "general", "pengantar", "Surat Pengantar Umum", "PGU", "general-cover-letter"],
  ["birth-certificate-referral-letter", "general", "pengantar", "Surat Keterangan Mohon Akta Kelahiran", "PAK", null],
  ["marriage-introduction-letter", "general", "pengantar", "Pengantar Nikah", "PNK", null],
  ["marriage-lodging", "general", "pengantar", "Surat Keterangan Numpang Nikah", "PNN", "numpang-nikah"],
  ["health-referral", "general", "pengantar", "Surat Pengantar Tes Kesehatan", "PKS", "health-referral"],
  ["judge-guardian", "general", "pengantar", "Surat Keterangan Wali Hakim", "PWH", "judge-guardian"],
  ["death-report", "general", "pengantar", "Laporan Kematian", "PLM", null],
  ["death-registration-report", "general", "pengantar", "Pelaporan Pencatatan Kematian", "PCK", null],
  ["birth-registration-report", "general", "pengantar", "Pelaporan Pencatatan Kelahiran", "PCL", null],
  ["out-of-domicile-birth-report", "general", "pengantar", "Laporan Kelahiran Luar Domisili", "PLD", null],
  ["bussiness-permit-letter", "permit", "perizinan", "Surat Keterangan Usaha", "IZU", "bussiness-permit-letter"],
  ["income-permit-letter", "permit", "perizinan", "Surat Keterangan Penghasilan", "KPH", "income-permit-letter"],
  ["event-permit-letter", "permit", "perizinan", "Surat Keterangan Keramaian", "IZK", "event-permit-letter"],
  ["travel-permit-letter-gov", "permit", "perizinan", "Surat Keterangan Jalan", "IPI", "travel-permit-letter-gov"],
  ["permit-followup-letter", "permit", "perizinan", "Surat Tindak Lanjut Permohonan Izin", "TLP", "permit-followup-letter"],
];